### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yoshi19841116** [yoshi19841116/furima-39202#24]
https://furima-39202.onrender.com

Basic認証のIDとパスワード
ID:[leokun]   パスワード[0529]

出品者用のメールアドレスとパスワード
メールアドレス[sample1@test]. パスワード [123456a]

購入者用のメールアドレスとパスワード
メールアドレス[hoge@hoge]. パスワード [123456a]

**Comment by snkw-works** [comment]
@yoshi19841116 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン状態の場合でも、自身が出品した商品の商品購入ページに遷移しようとすると、商品の販売状況に関わらずトップページに遷移するよう修正しましょう**
自身が出品した"売却済み"商品の購入ページに遷移しようとすると、エラーページに遷移してしまいます。

- [x] **購入画面にて、エラーハンドリングの際、重複したエラーメッセージが表示されないよう修正しましょう**
「Phone number can't be blank」が重複して表示されています。

<img width="797" alt="スクリーンショット 2023-09-09 12 24 32" src="https://github.com/yoshi19841116/furima-39202/assets/54050089/3d3ddfde-8609-48b6-b96e-5d5d44894d56">


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yoshi19841116** [comment]
レビュー確認とご指摘ありがとうございました。

修正し本番環境での確認しましたので、再度ご確認していただけたらと思います。

**Comment by snkw-works** [comment]
@yoshi19841116 さん、ご提出ありがとうございます‼︎
修正が確認でき、正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
